# Generated by Django 4.0.6 on 2022-07-29 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Phone number must be entered in the format:'+999999999'. Up to 15 digits is allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=256)),
                ('referral_code', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In-progress'), (2, 'Converted'), (3, 'Rejected')], default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.country')),
            ],
        ),
        migrations.CreateModel(
            name='WalkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('token_number', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.device')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vendor')),
            ],
        ),
    ]
